services:
  frontend:
    build: .
    expose:
      - 5173

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:5173"
    depends_on:
      - frontend
