# Generated by Django 5.1 on 2024-08-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogpost_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="img_name",
            field=models.CharField(default="default.jpg", max_length=200),
            preserve_default=False,
        ),
    ]
